server:
  port: ${server_port}

spring:
  application:
    name: recipe-platform-backend
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB
      max-file-size: 2MB

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Email Configuration (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.recipeplatform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: ${jwt_secret}
    expiration: ${jwt_expiration}

  file-upload:
    dir:  upload/images



